name: Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pylint libgirepository1.0-dev
      - name: Install dependencies
        run: |
          pip3 install PyGObject
          pip3 install PyYAML
      - name: Lint
        run: |
          pylint src/nautiterm/*.py
